---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: rhacs-config
  name: compliance-cluster
  namespace: rhacm-rhacs-config
spec:
  clusterSelector:
    matchLabels:
      'compliance-cluster': 'true'
