# kustomize build --enable-alpha-plugins rhacm-config/policy-generator/rhacs-central | oc apply -f -
generators:
  - policygenerator.yaml
commonLabels:
  manifest-group: rhacs-central
commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous