apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: rhacs-central-pg
  #annotations:
  #  argocd.argoproj.io/compare-options: IgnoreExtraneous
placementBindingDefaults:
  name: rhacs-central-pg-pb
policyDefaults:
  namespace: rhacm-rhacs-config
  # Use the name of an existing placement rule
  placement:
    placementRuleName: rhacs-central-cluster
  remediationAction: enforce
  severity: high
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
  #policySets: 
  #  - rhacs-operator
policies:
  - name: rhacs-central
    manifests:
      - path: manifests