---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: compliance-cis-scan-pb
  namespace: rhacm-rhacs-config
placementRef:
  name: compliance-cluster
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: compliance-cis-scan
    apiGroup: policy.open-cluster-management.io
    kind: Policy