apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: '{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").metadata.annotations "init-bundle.stackrox.io/created-at" hub}}'
    init-bundle.stackrox.io/expires-at: '{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").metadata.annotations "init-bundle.stackrox.io/expires-at" hub}}'
    init-bundle.stackrox.io/id: '{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").metadata.annotations "init-bundle.stackrox.io/id" hub}}'
    init-bundle.stackrox.io/name: '{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").metadata.annotations "init-bundle.stackrox.io/name" hub}}'
  name: sensor-tls
  namespace: stackrox
data:
  ca.pem: '{{hub fromSecret "stackrox" "sensor-tls" "ca.pem" hub}}'
  sensor-cert.pem: '{{hub fromSecret "stackrox" "sensor-tls" "sensor-cert.pem" hub}}'
  sensor-key.pem: '{{hub fromSecret "stackrox" "sensor-tls" "sensor-key.pem" hub}}'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: '{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").metadata.annotations "init-bundle.stackrox.io/created-at" hub}}'
    init-bundle.stackrox.io/expires-at: '{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").metadata.annotations "init-bundle.stackrox.io/expires-at" hub}}'
    init-bundle.stackrox.io/id: '{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").metadata.annotations "init-bundle.stackrox.io/id" hub}}'
    init-bundle.stackrox.io/name: '{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").metadata.annotations "init-bundle.stackrox.io/name" hub}}'
  name: admission-control-tls
  namespace: stackrox
data:
  admission-control-cert.pem: '{{hub fromSecret "stackrox" "admission-control-tls" "admission-control-cert.pem" hub}}'
  admission-control-key.pem: '{{hub fromSecret "stackrox" "admission-control-tls" "admission-control-key.pem" hub}}'
  ca.pem: '{{hub fromSecret "stackrox" "admission-control-tls" "ca.pem" hub}}'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: '{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").metadata.annotations "init-bundle.stackrox.io/created-at" hub}}'
    init-bundle.stackrox.io/expires-at: '{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").metadata.annotations "init-bundle.stackrox.io/expires-at" hub}}'
    init-bundle.stackrox.io/id: '{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").metadata.annotations "init-bundle.stackrox.io/id" hub}}'
    init-bundle.stackrox.io/name: '{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").metadata.annotations "init-bundle.stackrox.io/name" hub}}'
  name: collector-tls
  namespace: stackrox
data:
  ca.pem: '{{hub fromSecret "stackrox" "collector-tls" "ca.pem" hub}}'
  collector-cert.pem: '{{hub fromSecret "stackrox" "collector-tls" "collector-cert.pem" hub}}'
  collector-key.pem: '{{hub fromSecret "stackrox" "collector-tls" "collector-key.pem" hub}}'
