apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: crypto-and-goat
  namespace: rhacm-apps
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - crypto-and-goat
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: rhacm-config/policy-generator/bad-faith-workloads/manifests
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: crypto-and-goat
  name: crypto-and-goat-subscription-1
  namespace: rhacm-apps
spec:
  channel: ggithubcom-kenmoini-rhacm-config-for-rhacs-ns/ggithubcom-kenmoini-rhacm-config-for-rhacs
  placement:
    placementRef:
      kind: PlacementRule
      name: crypto-and-goat-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: crypto-and-goat
  name: crypto-and-goat-placement-1
  namespace: rhacm-apps
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
